---
- hosts: all
  tasks:
    - name: Copy Project
      copy:
        src: files/
        dest: Blog/
    - name: Deploy Compose
      community.docker.docker_compose:
        project_name: blog
        recreate: always
        remove_orphans: true
        project_src: Blog/
      register: compose_out
    - ansible.builtin.debug:
        var: compose_out
