---
- hosts: all
  tasks:
    - name: where am I
      command: "ls"
      register: dir_out
    - ansible.builtin.debug:
        var: dir_out
    - name: Copy Project
      copy:
        src: files/project/
        dest: Blog/
    - name: Create Stack
      community.docker.docker_compose:
        project_name: blog
        recreate: always
        remove_orphans: true
        project_src: Blog/
