---
- hosts: all
  tasks:
    - name: Create Network
      community.docker.docker_network:
        name: blog
    - name: Deploy Blog
      community.docker.docker_container:
        name: cms
        image: ghcr.io/sebasptsch/nextblog
        pull: true
        recreate: true
        networks:
          - blog
        ports:
          - "3001:3000"
        restart_policy: unless-stopped
