---
- hosts: all
  tasks:
    - name: Copy Project
      copy:
        src: .ansible/project/
        dest: Blog/
    - name: Create Stack
      community.docker.docker_compose:
        project_name: blog
        recreate: always
        remove_orphans: true
        project_src: Blog/
